<?php
echo '<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><title>Tam Cốc Sunset Homestay: Nơi Hòa Quyện Cùng Thiên Nhiên Và Nghệ Thuật Sống</title><style>';
echo '/* cspell:disable-file */';
echo '/* webkit printing magic: print all background colors */';
echo 'html {';
echo '-webkit-print-color-adjust: exact;';
echo '}';
echo '* {';
echo 'box-sizing: border-box;';
echo '-webkit-print-color-adjust: exact;';
echo '}';
echo '';
echo 'html,';
echo 'body {';
echo 'margin: 0;';
echo 'padding: 0;';
echo '}';
echo '@media only screen {';
echo 'body {';
echo 'margin: 2em auto;';
echo 'max-width: 900px;';
echo 'color: rgb(55, 53, 47);';
echo '}';
echo '}';
echo '';
echo 'body {';
echo 'line-height: 1.5;';
echo 'white-space: pre-wrap;';
echo '}';
echo '';
echo 'a,';
echo 'a.visited {';
echo 'color: inherit;';
echo 'text-decoration: underline;';
echo '}';
echo '';
echo '.pdf-relative-link-path {';
echo 'font-size: 80%;';
echo 'color: #444;';
echo '}';
echo '';
echo 'h1,';
echo 'h2,';
echo 'h3 {';
echo 'letter-spacing: -0.01em;';
echo 'line-height: 1.2;';
echo 'font-weight: 600;';
echo 'margin-bottom: 0;';
echo '}';
echo '';
echo '.page-title {';
echo 'font-size: 2.5rem;';
echo 'font-weight: 700;';
echo 'margin-top: 0;';
echo 'margin-bottom: 0.75em;';
echo '}';
echo '';
echo 'h1 {';
echo 'font-size: 1.875rem;';
echo 'margin-top: 1.875rem;';
echo '}';
echo '';
echo 'h2 {';
echo 'font-size: 1.5rem;';
echo 'margin-top: 1.5rem;';
echo '}';
echo '';
echo 'h3 {';
echo 'font-size: 1.25rem;';
echo 'margin-top: 1.25rem;';
echo '}';
echo '';
echo '.source {';
echo 'border: 1px solid #ddd;';
echo 'border-radius: 3px;';
echo 'padding: 1.5em;';
echo 'word-break: break-all;';
echo '}';
echo '';
echo '.callout {';
echo 'border-radius: 3px;';
echo 'padding: 1rem;';
echo '}';
echo '';
echo 'figure {';
echo 'margin: 1.25em 0;';
echo 'page-break-inside: avoid;';
echo '}';
echo '';
echo 'figcaption {';
echo 'opacity: 0.5;';
echo 'font-size: 85%;';
echo 'margin-top: 0.5em;';
echo '}';
echo '';
echo 'mark {';
echo 'background-color: transparent;';
echo '}';
echo '';
echo '.indented {';
echo 'padding-left: 1.5em;';
echo '}';
echo '';
echo 'hr {';
echo 'background: transparent;';
echo 'display: block;';
echo 'width: 100%;';
echo 'height: 1px;';
echo 'visibility: visible;';
echo 'border: none;';
echo 'border-bottom: 1px solid rgba(55, 53, 47, 0.09);';
echo '}';
echo '';
echo 'img {';
echo 'max-width: 100%;';
echo '}';
echo '';
echo '@media only print {';
echo 'img {';
echo 'max-height: 100vh;';
echo 'object-fit: contain;';
echo '}';
echo '}';
echo '';
echo '@page {';
echo 'margin: 1in;';
echo '}';
echo '';
echo '.collection-content {';
echo 'font-size: 0.875rem;';
echo '}';
echo '';
echo '.column-list {';
echo 'display: flex;';
echo 'justify-content: space-between;';
echo '}';
echo '';
echo '.column {';
echo 'padding: 0 1em;';
echo '}';
echo '';
echo '.column:first-child {';
echo 'padding-left: 0;';
echo '}';
echo '';
echo '.column:last-child {';
echo 'padding-right: 0;';
echo '}';
echo '';
echo '.table_of_contents-item {';
echo 'display: block;';
echo 'font-size: 0.875rem;';
echo 'line-height: 1.3;';
echo 'padding: 0.125rem;';
echo '}';
echo '';
echo '.table_of_contents-indent-1 {';
echo 'margin-left: 1.5rem;';
echo '}';
echo '';
echo '.table_of_contents-indent-2 {';
echo 'margin-left: 3rem;';
echo '}';
echo '';
echo '.table_of_contents-indent-3 {';
echo 'margin-left: 4.5rem;';
echo '}';
echo '';
echo '.table_of_contents-link {';
echo 'text-decoration: none;';
echo 'opacity: 0.7;';
echo 'border-bottom: 1px solid rgba(55, 53, 47, 0.18);';
echo '}';
echo '';
echo 'table,';
echo 'th,';
echo 'td {';
echo 'border: 1px solid rgba(55, 53, 47, 0.09);';
echo 'border-collapse: collapse;';
echo '}';
echo '';
echo 'table {';
echo 'border-left: none;';
echo 'border-right: none;';
echo '}';
echo '';
echo 'th,';
echo 'td {';
echo 'font-weight: normal;';
echo 'padding: 0.25em 0.5em;';
echo 'line-height: 1.5;';
echo 'min-height: 1.5em;';
echo 'text-align: left;';
echo '}';
echo '';
echo 'th {';
echo 'color: rgba(55, 53, 47, 0.6);';
echo '}';
echo '';
echo 'ol,';
echo 'ul {';
echo 'margin: 0;';
echo 'margin-block-start: 0.6em;';
echo 'margin-block-end: 0.6em;';
echo '}';
echo '';
echo 'li > ol:first-child,';
echo 'li > ul:first-child {';
echo 'margin-block-start: 0.6em;';
echo '}';
echo '';
echo 'ul > li {';
echo 'list-style: disc;';
echo '}';
echo '';
echo 'ul.to-do-list {';
echo 'padding-inline-start: 0;';
echo '}';
echo '';
echo 'ul.to-do-list > li {';
echo 'list-style: none;';
echo '}';
echo '';
echo '.to-do-children-checked {';
echo 'text-decoration: line-through;';
echo 'opacity: 0.375;';
echo '}';
echo '';
echo 'ul.toggle > li {';
echo 'list-style: none;';
echo '}';
echo '';
echo 'ul {';
echo 'padding-inline-start: 1.7em;';
echo '}';
echo '';
echo 'ul > li {';
echo 'padding-left: 0.1em;';
echo '}';
echo '';
echo 'ol {';
echo 'padding-inline-start: 1.6em;';
echo '}';
echo '';
echo 'ol > li {';
echo 'padding-left: 0.2em;';
echo '}';
echo '';
echo '.mono ol {';
echo 'padding-inline-start: 2em;';
echo '}';
echo '';
echo '.mono ol > li {';
echo 'text-indent: -0.4em;';
echo '}';
echo '';
echo '.toggle {';
echo 'padding-inline-start: 0em;';
echo 'list-style-type: none;';
echo '}';
echo '';
echo '/* Indent toggle children */';
echo '.toggle > li > details {';
echo 'padding-left: 1.7em;';
echo '}';
echo '';
echo '.toggle > li > details > summary {';
echo 'margin-left: -1.1em;';
echo '}';
echo '';
echo '.selected-value {';
echo 'display: inline-block;';
echo 'padding: 0 0.5em;';
echo 'background: rgba(206, 205, 202, 0.5);';
echo 'border-radius: 3px;';
echo 'margin-right: 0.5em;';
echo 'margin-top: 0.3em;';
echo 'margin-bottom: 0.3em;';
echo 'white-space: nowrap;';
echo '}';
echo '';
echo '.collection-title {';
echo 'display: inline-block;';
echo 'margin-right: 1em;';
echo '}';
echo '';
echo '.page-description {';
echo 'margin-bottom: 2em;';
echo '}';
echo '';
echo '.simple-table {';
echo 'margin-top: 1em;';
echo 'font-size: 0.875rem;';
echo 'empty-cells: show;';
echo '}';
echo '.simple-table td {';
echo 'height: 29px;';
echo 'min-width: 120px;';
echo '}';
echo '';
echo '.simple-table th {';
echo 'height: 29px;';
echo 'min-width: 120px;';
echo '}';
echo '';
echo '.simple-table-header-color {';
echo 'background: rgb(247, 246, 243);';
echo 'color: black;';
echo '}';
echo '.simple-table-header {';
echo 'font-weight: 500;';
echo '}';
echo '';
echo 'time {';
echo 'opacity: 0.5;';
echo '}';
echo '';
echo '.icon {';
echo 'display: inline-block;';
echo 'max-width: 1.2em;';
echo 'max-height: 1.2em;';
echo 'text-decoration: none;';
echo 'vertical-align: text-bottom;';
echo 'margin-right: 0.5em;';
echo '}';
echo '';
echo 'img.icon {';
echo 'border-radius: 3px;';
echo '}';
echo '';
echo '.user-icon {';
echo 'width: 1.5em;';
echo 'height: 1.5em;';
echo 'border-radius: 100%;';
echo 'margin-right: 0.5rem;';
echo '}';
echo '';
echo '.user-icon-inner {';
echo 'font-size: 0.8em;';
echo '}';
echo '';
echo '.text-icon {';
echo 'border: 1px solid #000;';
echo 'text-align: center;';
echo '}';
echo '';
echo '.page-cover-image {';
echo 'display: block;';
echo 'object-fit: cover;';
echo 'width: 100%;';
echo 'max-height: 30vh;';
echo '}';
echo '';
echo '.page-header-icon {';
echo 'font-size: 3rem;';
echo 'margin-bottom: 1rem;';
echo '}';
echo '';
echo '.page-header-icon-with-cover {';
echo 'margin-top: -0.72em;';
echo 'margin-left: 0.07em;';
echo '}';
echo '';
echo '.page-header-icon img {';
echo 'border-radius: 3px;';
echo '}';
echo '';
echo '.link-to-page {';
echo 'margin: 1em 0;';
echo 'padding: 0;';
echo 'border: none;';
echo 'font-weight: 500;';
echo '}';
echo '';
echo 'p > .user {';
echo 'opacity: 0.5;';
echo '}';
echo '';
echo 'td > .user,';
echo 'td > time {';
echo 'white-space: nowrap;';
echo '}';
echo '';
echo 'input[type="checkbox"] {';
echo 'transform: scale(1.5);';
echo 'margin-right: 0.6em;';
echo 'vertical-align: middle;';
echo '}';
echo '';
echo 'p {';
echo 'margin-top: 0.5em;';
echo 'margin-bottom: 0.5em;';
echo '}';
echo '';
echo '.image {';
echo 'border: none;';
echo 'margin: 1.5em 0;';
echo 'padding: 0;';
echo 'border-radius: 0;';
echo 'text-align: center;';
echo '}';
echo '';
echo '.code,';
echo 'code {';
echo 'background: rgba(135, 131, 120, 0.15);';
echo 'border-radius: 3px;';
echo 'padding: 0.2em 0.4em;';
echo 'border-radius: 3px;';
echo 'font-size: 85%;';
echo 'tab-size: 2;';
echo '}';
echo '';
echo 'code {';
echo 'color: #eb5757;';
echo '}';
echo '';
echo '.code {';
echo 'padding: 1.5em 1em;';
echo '}';
echo '';
echo '.code-wrap {';
echo 'white-space: pre-wrap;';
echo 'word-break: break-all;';
echo '}';
echo '';
echo '.code > code {';
echo 'background: none;';
echo 'padding: 0;';
echo 'font-size: 100%;';
echo 'color: inherit;';
echo '}';
echo '';
echo 'blockquote {';
echo 'font-size: 1.25em;';
echo 'margin: 1em 0;';
echo 'padding-left: 1em;';
echo 'border-left: 3px solid rgb(55, 53, 47);';
echo '}';
echo '';
echo '.bookmark {';
echo 'text-decoration: none;';
echo 'max-height: 8em;';
echo 'padding: 0;';
echo 'display: flex;';
echo 'width: 100%;';
echo 'align-items: stretch;';
echo '}';
echo '';
echo '.bookmark-title {';
echo 'font-size: 0.85em;';
echo 'overflow: hidden;';
echo 'text-overflow: ellipsis;';
echo 'height: 1.75em;';
echo 'white-space: nowrap;';
echo '}';
echo '';
echo '.bookmark-text {';
echo 'display: flex;';
echo 'flex-direction: column;';
echo '}';
echo '';
echo '.bookmark-info {';
echo 'flex: 4 1 180px;';
echo 'padding: 12px 14px 14px;';
echo 'display: flex;';
echo 'flex-direction: column;';
echo 'justify-content: space-between;';
echo '}';
echo '';
echo '.bookmark-image {';
echo 'width: 33%;';
echo 'flex: 1 1 180px;';
echo 'display: block;';
echo 'position: relative;';
echo 'object-fit: cover;';
echo 'border-radius: 1px;';
echo '}';
echo '';
echo '.bookmark-description {';
echo 'color: rgba(55, 53, 47, 0.6);';
echo 'font-size: 0.75em;';
echo 'overflow: hidden;';
echo 'max-height: 4.5em;';
echo 'word-break: break-word;';
echo '}';
echo '';
echo '.bookmark-href {';
echo 'font-size: 0.75em;';
echo 'margin-top: 0.25em;';
echo '}';
echo '';
echo '.sans { font-family: ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol"; }';
echo '.code { font-family: "SFMono-Regular", Menlo, Consolas, "PT Mono", "Liberation Mono", Courier, monospace; }';
echo '.serif { font-family: Lyon-Text, Georgia, ui-serif, serif; }';
echo '.mono { font-family: iawriter-mono, Nitti, Menlo, Courier, monospace; }';
echo '.pdf .sans { font-family: Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol", 'Twemoji', 'Noto Color Emoji', 'Noto Sans CJK JP'; }';
echo '.pdf:lang(zh-CN) .sans { font-family: Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol", 'Twemoji', 'Noto Color Emoji', 'Noto Sans CJK SC'; }';
echo '.pdf:lang(zh-TW) .sans { font-family: Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol", 'Twemoji', 'Noto Color Emoji', 'Noto Sans CJK TC'; }';
echo '.pdf:lang(ko-KR) .sans { font-family: Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol", 'Twemoji', 'Noto Color Emoji', 'Noto Sans CJK KR'; }';
echo '.pdf .code { font-family: Source Code Pro, "SFMono-Regular", Menlo, Consolas, "PT Mono", "Liberation Mono", Courier, monospace, 'Twemoji', 'Noto Color Emoji', 'Noto Sans Mono CJK JP'; }';
echo '.pdf:lang(zh-CN) .code { font-family: Source Code Pro, "SFMono-Regular", Menlo, Consolas, "PT Mono", "Liberation Mono", Courier, monospace, 'Twemoji', 'Noto Color Emoji', 'Noto Sans Mono CJK SC'; }';
echo '.pdf:lang(zh-TW) .code { font-family: Source Code Pro, "SFMono-Regular", Menlo, Consolas, "PT Mono", "Liberation Mono", Courier, monospace, 'Twemoji', 'Noto Color Emoji', 'Noto Sans Mono CJK TC'; }';
echo '.pdf:lang(ko-KR) .code { font-family: Source Code Pro, "SFMono-Regular", Menlo, Consolas, "PT Mono", "Liberation Mono", Courier, monospace, 'Twemoji', 'Noto Color Emoji', 'Noto Sans Mono CJK KR'; }';
echo '.pdf .serif { font-family: PT Serif, Lyon-Text, Georgia, ui-serif, serif, 'Twemoji', 'Noto Color Emoji', 'Noto Serif CJK JP'; }';
echo '.pdf:lang(zh-CN) .serif { font-family: PT Serif, Lyon-Text, Georgia, ui-serif, serif, 'Twemoji', 'Noto Color Emoji', 'Noto Serif CJK SC'; }';
echo '.pdf:lang(zh-TW) .serif { font-family: PT Serif, Lyon-Text, Georgia, ui-serif, serif, 'Twemoji', 'Noto Color Emoji', 'Noto Serif CJK TC'; }';
echo '.pdf:lang(ko-KR) .serif { font-family: PT Serif, Lyon-Text, Georgia, ui-serif, serif, 'Twemoji', 'Noto Color Emoji', 'Noto Serif CJK KR'; }';
echo '.pdf .mono { font-family: PT Mono, iawriter-mono, Nitti, Menlo, Courier, monospace, 'Twemoji', 'Noto Color Emoji', 'Noto Sans Mono CJK JP'; }';
echo '.pdf:lang(zh-CN) .mono { font-family: PT Mono, iawriter-mono, Nitti, Menlo, Courier, monospace, 'Twemoji', 'Noto Color Emoji', 'Noto Sans Mono CJK SC'; }';
echo '.pdf:lang(zh-TW) .mono { font-family: PT Mono, iawriter-mono, Nitti, Menlo, Courier, monospace, 'Twemoji', 'Noto Color Emoji', 'Noto Sans Mono CJK TC'; }';
echo '.pdf:lang(ko-KR) .mono { font-family: PT Mono, iawriter-mono, Nitti, Menlo, Courier, monospace, 'Twemoji', 'Noto Color Emoji', 'Noto Sans Mono CJK KR'; }';
echo '.highlight-default {';
echo 'color: rgba(55, 53, 47, 1);';
echo '}';
echo '.highlight-gray {';
echo 'color: rgba(120, 119, 116, 1);';
echo 'fill: rgba(120, 119, 116, 1);';
echo '}';
echo '.highlight-brown {';
echo 'color: rgba(159, 107, 83, 1);';
echo 'fill: rgba(159, 107, 83, 1);';
echo '}';
echo '.highlight-orange {';
echo 'color: rgba(217, 115, 13, 1);';
echo 'fill: rgba(217, 115, 13, 1);';
echo '}';
echo '.highlight-yellow {';
echo 'color: rgba(203, 145, 47, 1);';
echo 'fill: rgba(203, 145, 47, 1);';
echo '}';
echo '.highlight-teal {';
echo 'color: rgba(68, 131, 97, 1);';
echo 'fill: rgba(68, 131, 97, 1);';
echo '}';
echo '.highlight-blue {';
echo 'color: rgba(51, 126, 169, 1);';
echo 'fill: rgba(51, 126, 169, 1);';
echo '}';
echo '.highlight-purple {';
echo 'color: rgba(144, 101, 176, 1);';
echo 'fill: rgba(144, 101, 176, 1);';
echo '}';
echo '.highlight-pink {';
echo 'color: rgba(193, 76, 138, 1);';
echo 'fill: rgba(193, 76, 138, 1);';
echo '}';
echo '.highlight-red {';
echo 'color: rgba(212, 76, 71, 1);';
echo 'fill: rgba(212, 76, 71, 1);';
echo '}';
echo '.highlight-gray_background {';
echo 'background: rgba(241, 241, 239, 1);';
echo '}';
echo '.highlight-brown_background {';
echo 'background: rgba(244, 238, 238, 1);';
echo '}';
echo '.highlight-orange_background {';
echo 'background: rgba(251, 236, 221, 1);';
echo '}';
echo '.highlight-yellow_background {';
echo 'background: rgba(251, 243, 219, 1);';
echo '}';
echo '.highlight-teal_background {';
echo 'background: rgba(237, 243, 236, 1);';
echo '}';
echo '.highlight-blue_background {';
echo 'background: rgba(231, 243, 248, 1);';
echo '}';
echo '.highlight-purple_background {';
echo 'background: rgba(244, 240, 247, 0.8);';
echo '}';
echo '.highlight-pink_background {';
echo 'background: rgba(249, 238, 243, 0.8);';
echo '}';
echo '.highlight-red_background {';
echo 'background: rgba(253, 235, 236, 1);';
echo '}';
echo '.block-color-default {';
echo 'color: inherit;';
echo 'fill: inherit;';
echo '}';
echo '.block-color-gray {';
echo 'color: rgba(120, 119, 116, 1);';
echo 'fill: rgba(120, 119, 116, 1);';
echo '}';
echo '.block-color-brown {';
echo 'color: rgba(159, 107, 83, 1);';
echo 'fill: rgba(159, 107, 83, 1);';
echo '}';
echo '.block-color-orange {';
echo 'color: rgba(217, 115, 13, 1);';
echo 'fill: rgba(217, 115, 13, 1);';
echo '}';
echo '.block-color-yellow {';
echo 'color: rgba(203, 145, 47, 1);';
echo 'fill: rgba(203, 145, 47, 1);';
echo '}';
echo '.block-color-teal {';
echo 'color: rgba(68, 131, 97, 1);';
echo 'fill: rgba(68, 131, 97, 1);';
echo '}';
echo '.block-color-blue {';
echo 'color: rgba(51, 126, 169, 1);';
echo 'fill: rgba(51, 126, 169, 1);';
echo '}';
echo '.block-color-purple {';
echo 'color: rgba(144, 101, 176, 1);';
echo 'fill: rgba(144, 101, 176, 1);';
echo '}';
echo '.block-color-pink {';
echo 'color: rgba(193, 76, 138, 1);';
echo 'fill: rgba(193, 76, 138, 1);';
echo '}';
echo '.block-color-red {';
echo 'color: rgba(212, 76, 71, 1);';
echo 'fill: rgba(212, 76, 71, 1);';
echo '}';
echo '.block-color-gray_background {';
echo 'background: rgba(241, 241, 239, 1);';
echo '}';
echo '.block-color-brown_background {';
echo 'background: rgba(244, 238, 238, 1);';
echo '}';
echo '.block-color-orange_background {';
echo 'background: rgba(251, 236, 221, 1);';
echo '}';
echo '.block-color-yellow_background {';
echo 'background: rgba(251, 243, 219, 1);';
echo '}';
echo '.block-color-teal_background {';
echo 'background: rgba(237, 243, 236, 1);';
echo '}';
echo '.block-color-blue_background {';
echo 'background: rgba(231, 243, 248, 1);';
echo '}';
echo '.block-color-purple_background {';
echo 'background: rgba(244, 240, 247, 0.8);';
echo '}';
echo '.block-color-pink_background {';
echo 'background: rgba(249, 238, 243, 0.8);';
echo '}';
echo '.block-color-red_background {';
echo 'background: rgba(253, 235, 236, 1);';
echo '}';
echo '.select-value-color-interactiveBlue { background-color: rgba(35, 131, 226, .07); }';
echo '.select-value-color-pink { background-color: rgba(245, 224, 233, 1); }';
echo '.select-value-color-purple { background-color: rgba(232, 222, 238, 1); }';
echo '.select-value-color-green { background-color: rgba(219, 237, 219, 1); }';
echo '.select-value-color-gray { background-color: rgba(227, 226, 224, 1); }';
echo '.select-value-color-translucentGray { background-color: rgba(255, 255, 255, 0.0375); }';
echo '.select-value-color-orange { background-color: rgba(250, 222, 201, 1); }';
echo '.select-value-color-brown { background-color: rgba(238, 224, 218, 1); }';
echo '.select-value-color-red { background-color: rgba(255, 226, 221, 1); }';
echo '.select-value-color-yellow { background-color: rgba(253, 236, 200, 1); }';
echo '.select-value-color-blue { background-color: rgba(211, 229, 239, 1); }';
echo '.select-value-color-pageGlass { background-color: undefined; }';
echo '.select-value-color-washGlass { background-color: undefined; }';
echo '';
echo '.checkbox {';
echo 'display: inline-flex;';
echo 'vertical-align: text-bottom;';
echo 'width: 16;';
echo 'height: 16;';
echo 'background-size: 16px;';
echo 'margin-left: 2px;';
echo 'margin-right: 5px;';
echo '}';
echo '';
echo '.checkbox-on {';
echo 'background-image: url("data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2216%22%20height%3D%2216%22%20viewBox%3D%220%200%2016%2016%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Crect%20width%3D%2216%22%20height%3D%2216%22%20fill%3D%22%2358A9D7%22%2F%3E%0A%3Cpath%20d%3D%22M6.71429%2012.2852L14%204.9995L12.7143%203.71436L6.71429%209.71378L3.28571%206.2831L2%207.57092L6.71429%2012.2852Z%22%20fill%3D%22white%22%2F%3E%0A%3C%2Fsvg%3E");';
echo '}';
echo '';
echo '.checkbox-off {';
echo 'background-image: url("data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2216%22%20height%3D%2216%22%20viewBox%3D%220%200%2016%2016%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%3Crect%20x%3D%220.75%22%20y%3D%220.75%22%20width%3D%2214.5%22%20height%3D%2214.5%22%20fill%3D%22white%22%20stroke%3D%22%2336352F%22%20stroke-width%3D%221.5%22%2F%3E%0A%3C%2Fsvg%3E");';
echo '}';
echo '';
echo '</style></head><body><article id="46091ec3-e2e3-44a9-ad85-802fcef0e8be" class="page sans"><header><img class="page-cover-image" src="Tam%20Co%CC%82%CC%81c%20Sunset%20Homestay%20No%CC%9Bi%20Ho%CC%80a%20Quye%CC%A3%CC%82n%20Cu%CC%80ng%20%2046091ec3e2e344a9ad85802fcef0e8be/trang-an-ninh-binh.jpeg" style="object-position:center 50%"/><div class="page-header-icon page-header-icon-with-cover"><img class="icon" src="Tam%20Co%CC%82%CC%81c%20Sunset%20Homestay%20No%CC%9Bi%20Ho%CC%80a%20Quye%CC%A3%CC%82n%20Cu%CC%80ng%20%2046091ec3e2e344a9ad85802fcef0e8be/logo.jpg"/></div><h1 class="page-title"><em>Tam Cốc Sunset Homestay: Nơi Hòa Quyện Cùng Thiên Nhiên Và Nghệ Thuật Sống</em></h1><p class="page-description"></p></header><div class="page-body"><p id="2b0ea1fd-e560-47e5-9a49-dd6b2871e693" class="">Tam Cốc Sunset Homestay, một biểu tượng mới của sự hòa quyện giữa thiên nhiên tươi đẹp và nghệ thuật sống, đã chính thức khai trương tại vùng đất thơ mộng Ninh Bình vào ngày 15/02/2023. Với sứ mệnh mang đến những trải nghiệm nghỉ dưỡng lưu trú độc đáo và thư giãn tối đa, homestay này đã nhanh chóng thu hút sự chú ý của du khách và những người yêu thích thiên nhiên.</p><figure id="b1c8c5ab-db41-40bc-89c2-4404185ed21d" class="image"><a href="Tam%20Co%CC%82%CC%81c%20Sunset%20Homestay%20No%CC%9Bi%20Ho%CC%80a%20Quye%CC%A3%CC%82n%20Cu%CC%80ng%20%2046091ec3e2e344a9ad85802fcef0e8be/ngoai-that-tam-coc-sunset-homestay_(3).jpg"><img style="width:1907px" src="Tam%20Co%CC%82%CC%81c%20Sunset%20Homestay%20No%CC%9Bi%20Ho%CC%80a%20Quye%CC%A3%CC%82n%20Cu%CC%80ng%20%2046091ec3e2e344a9ad85802fcef0e8be/ngoai-that-tam-coc-sunset-homestay_(3).jpg"/></a></figure><h2 id="5a07f99c-a3c2-42bc-8568-95279bdb446a" class=""><strong>Kết Nối Với Thiên Nhiên</strong></h2><p id="b41aeef6-fd3a-4df7-9f94-49456c5a073f" class="">Tam Cốc Sunset Homestay nằm tại vị trí đắc địa, gần trung tâm thành phố Ninh Bình và các điểm du lịch nổi tiếng như Động Tam Cốc, Bich Dong Pagoda, Khu du lịch sinh thái Vườn Chim Thung Nham, Trang An Eco Tourism Complex và Cố đô Hoa Lư. Khách hàng khi lựa chọn homestay này không chỉ có cơ hội khám phá những danh lam thắng cảnh độc đáo mà còn được hòa mình vào không gian thiên nhiên yên bình, thoải mái.</p><h2 id="92d2d9cb-2e4a-4830-aed7-818be020dcfc" class=""><strong>Trải Nghiệm Lưu Trú Tại Tam Cốc Sunset Homestay</strong></h2><p id="ed048337-1d45-4d3b-8728-a04bea9b49d2" class="">Với tổng cộng 5 phòng lớn, mỗi phòng được thiết kế với phong cách hiện đại, tinh tế và tiện nghi đầy đủ để đáp ứng nhu cầu của khách hàng. Các phòng có ban công và phòng nhìn ra vườn đem lại không gian thư giãn, yên tĩnh và gần gũi với thiên nhiên. Được trang bị điều hòa, tủ lạnh, máy sấy tóc, ấm đun nước và các vật dụng cá nhân, mỗi phòng tại Tam Cốc Sunset Homestay đều mang đến sự thoải mái tối đa cho du khách.</p><figure id="d037fe6e-8d5e-468a-9edd-a1b838df5f6c" class="image"><a href="Tam%20Co%CC%82%CC%81c%20Sunset%20Homestay%20No%CC%9Bi%20Ho%CC%80a%20Quye%CC%A3%CC%82n%20Cu%CC%80ng%20%2046091ec3e2e344a9ad85802fcef0e8be/noi-that-tam-coc-sunset-homestay_(2).jpg"><img style="width:2560px" src="Tam%20Co%CC%82%CC%81c%20Sunset%20Homestay%20No%CC%9Bi%20Ho%CC%80a%20Quye%CC%A3%CC%82n%20Cu%CC%80ng%20%2046091ec3e2e344a9ad85802fcef0e8be/noi-that-tam-coc-sunset-homestay_(2).jpg"/></a></figure><h2 id="5975216b-bbb7-4317-a8c9-571779d3f1aa" class=""><strong>Khoảnh Khắc Hoàng Hôn Rực Rỡ</strong></h2><p id="e9dedc80-ff44-4362-af8f-3e733730e8f3" class="">Tại tầng thượng của homestay, du khách sẽ được đắm mình trong không gian ấn tượng với khu vực ăn uống, tiếp khách và khu vườn. Đây là nơi lý tưởng để thả mình tận hưởng khoảnh khắc hoàng hôn rực rỡ và thư giãn sau một ngày dạo chơi và khám phá. Tầng thượng còn là nơi hoàn hảo để gặp gỡ bạn bè, gia đình hoặc tổ chức những buổi tụ tập thú vị.</p><figure id="409d0a95-30e6-4a57-8f78-20fc2dc4b9c4" class="image"><a href="Tam%20Co%CC%82%CC%81c%20Sunset%20Homestay%20No%CC%9Bi%20Ho%CC%80a%20Quye%CC%A3%CC%82n%20Cu%CC%80ng%20%2046091ec3e2e344a9ad85802fcef0e8be/ngoai-that-tam-coc-sunset-homestay_(7).jpg"><img style="width:1280px" src="Tam%20Co%CC%82%CC%81c%20Sunset%20Homestay%20No%CC%9Bi%20Ho%CC%80a%20Quye%CC%A3%CC%82n%20Cu%CC%80ng%20%2046091ec3e2e344a9ad85802fcef0e8be/ngoai-that-tam-coc-sunset-homestay_(7).jpg"/></a></figure><h2 id="b3e4b95b-e2e7-435a-a84e-4e588ca1325e" class=""><strong>Trải Nghiệm Đa Dạng Và Phong Phú</strong></h2><p id="7fd16e64-cd42-4374-acc2-cb35d260810a" class="">Homestay không chỉ đơn thuần là nơi lưu trú nghỉ dưỡng mà còn mang đến cho du khách nhiều trải nghiệm thú vị. Bữa sáng tại Tam Cốc Sunset Homestay được chuẩn bị công phu với nhiều lựa chọn tùy theo khẩu vị của du khách. Không gian chỗ đậu xe miễn phí, dịch vụ cho thuê xe đạp, xe máy và dịch vụ đưa đón sân bay đều giúp du khách tự do khám phá vùng đất thơ mộng này.</p><h2 id="3d1b12af-96fd-4dcb-bf00-794739ce9600" class=""><strong>Liên Hệ Và Đặt Phòng Ngay Hôm Nay</strong></h2><p id="ef7678b5-90ad-4cc3-8f75-5b2997d20e1e" class="">Để trải nghiệm những khoảnh khắc đáng nhớ tại Tam Cốc Sunset Homestay, hãy liên hệ ngay:</p><p id="10a41dee-de8c-4ad7-ae31-5f756c8e9558" class=""><strong>Tam Cốc Sunset Homestay';
echo 'Địa chỉ:</strong> Hành Cung, Ninh Thắng, Hoa Lư, Ninh Bình';
echo '<strong>Điện thoại:</strong> 0376140303';
echo '<strong>Email:</strong> <a href="mailto:tamcocsunsethomestay@gmail.com">tamcocsunsethomestay@gmail.com</a><strong>';
echo 'Website:</strong> <a href="https://tamcocsunsethomestay.com/">https://tamcocsunsethomestay.com/</a><strong>';
echo 'Google Map:</strong> <a href="https://www.google.com/maps?cid=13630179987910901892">https://www.google.com/maps?cid=13630179987910901892</a></p><p id="8bd684f2-2f6e-4fe9-bb27-c926497ee6c7" class="">Khám phá sự kết hợp tuyệt vời giữa thiên nhiên và nghệ thuật sống tại Tam Cốc Sunset Homestay. Hãy đặt phòng ngay hôm nay để tận hưởng một kỳ nghỉ đáng nhớ và thư giãn tối đa.</p><p id="32137f9f-3e8d-4045-b71e-244aa3c85e8c" class=""><em>Ngày phát hành:</em> 12/08/2023</p></div></article></body></html>';
?>